SELECT DEPTNO,COUNT(*)FROM EMP WHERE NOT DEPTNO=10 GROUP BY DEPTNO;
SELECT JOB,COUNT(*) FROM EMP WHERE JOB NOT IN ('SALESMAN') GROUP BY JOB;
SELECT DEPTNO,COUNT(*) FROM EMP  GROUP BY DEPTNO HAVING COUNT(*)>=3;
SELECT JOB,COUNT(*) FROM EMP GROUP BY JOB HAVING COUNT(*)=4;
SELECT ENAME,COUNT(*) FROM EMP GROUP  BY ENAME HAVING COUNT(*)>1;
SELECT SAL,COUNT(*) FROM EMP GROUP  BY SAL HAVING COUNT(*)>1;
SELECT SAL FROM EMP ORDER BY SAL ASC;



SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB!='PRESIDENT'GROUP BY DEPTNO;
SELECT JOB,SUM(SAL) FROM EMP GROUP BY JOB;
SELECT JOB,COUNT(*) FROM EMP WHERE JOB='MANAGER'GROUP BY JOB;
SELECT DEPTNO,AVG(SAL) FROM EMP WHERE DEPTNO!=20 GROUP BY DEPTNO;
SELECT JOB,COUNT(*) FROM EMP WHERE JOB LIKE '%A%' GROUP BY JOB;
SELECT DEPTNO,COUNT(*),AVG(SAL) FROM EMP WHERE SAL>2000 GROUP BY DEPTNO;
SELECT DEPTNO,SUM(SAL) FROM EMP WHERE JOB='SALESMAN' GROUP BY DEPTNO;
SELECT JOB,COUNT(EMPNO),MAX(SAL) FROM EMP GROUP BY JOB;
SELECT DEPTNO,MAX(SAL) FROM EMP GROUP BY DEPTNO;
SELECT SAL,COUNT(*) FROM EMP GROUP BY SAL;



SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB='CLERK' GROUP BY DEPTNO HAVING COUNT(*)>=2;
SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=4;
SELECT COUNT(*),SAL FROM EMP WHERE SAL>1200 GROUP BY SAL HAVING SUM(SAL)>3800;
SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB='MANAGER' GROUP BY DEPTNO HAVING COUNT(*)=2;
SELECT JOB,MAX(SAL) FROM EMP GROUP BY JOB HAVING MAX(SAL)>2600;
SELECT SAL FROM EMP GROUP BY SAL HAVING COUNT(SAL)>1;
SELECT HIREDATE FROM EMP GROUP BY HIREDATE HAVING COUNT(*)>1;
SELECT DEPTNO,AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)<3000;
SELECT DEPTNO FROM EMP WHERE (ENAME LIKE'%A%' OR ENAME LIKE '%S%') GROUP BY DEPTNO HAVING COUNT(*)>=3;
SELECT JOB,MIN(SAL),MAX(SAL) FROM EMP GROUP BY JOB HAVING MIN(SAL)>1000 AND MAX(SAL)<5000;



SELECT JOB,SUM(SAL) FROM EMP GROUP BY JOB;
SELECT HIREDATE FROM EMP GROUP BY HIREDATE HAVING COUNT(*)>=3;
SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING (COUNT(*)>2 AND SUM(SAL)>9000);
SELECT COUNT(*),AVG(SAL) FROM EMP  WHERE SAL>COMM GROUP BY DEPTNO;
SELECT SAL FROM EMP GROUP BY SAL HAVING COUNT(*)>1;
SELECT ENAME FROM EMP GROUP BY ENAME HAVING COUNT(*)>1;
SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) BETWEEN 2500 AND 3000;
SELECT  COUNT(*) FROM EMP WHERE (JOB='MANAGER' OR JOB='ANALYST') AND SAL LIKE '%0' GROUP BY DEPTNO ;
SELECT COUNT(*) FROM EMP WHERE JOB='CLERK'GROUP BY DEPTNO;
SELECT DEPTNO,MAX(SAL) FROM EMP WHERE JOB='MANAGER' GROUP BY DEPTNO;



