SELECT ENAME FROM EMP WHERE SAL>(SELECT SAL FROM employee.EMP,department.DEPT WHERE ENAME='SCOTT' AND DNAME='ACCOUNTING');
SELECT * FROM EMPLOYEE.EMP WHERE JOB='MANAGER' AND  DEPTNO IN(SELECT DEPTNO FROM DEPARTMENT.DEPT WHERE LOC='CHICAGO') ;
SELECT ENAME,SAL FROM EMP WHERE SAL>(SELECT SAL FROM employee.EMP WHERE  ENAME='KING' AND DEPTNO=(SELECT DEPTNO FROM DEPARTMENT.DEPT WHERE DNAME='ACCOUNTING'));
SELECT * FROM EMP WHERE JOB='SALESMAN' AND DEPTNO=(SELECT DEPTNO FROM DEPARTMENT.DEPT WHERE DNAME='SALES');
SELECT ENAME,SAL,JOB,HIREDATE FROM EMP WHERE HIREDATE< (SELECT HIREDATE FROM EMP WHERE ENAME='KING' AND DEPTNO IN 
(SELECT DEPTNO FROM DEPARTMENT.DEPT WHERE DNAME='OPERATIONS'));
SELECT ENAME FROM  EMP WHERE DEPTNO IN(SELECT DEPTNO FROM DEPARTMENT.DEPT WHERE DNAME LIKE '%S');
SELECT DNAME FROM DEPARTMENT.DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMPLOYEE.EMP WHERE ENAME LIKE '%A%');
SELECT DNAME,LOC FROM department.DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMPLOYEE.EMP WHERE SAL=800);
SELECT DNAME FROM DEPARTMENT.DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMPLOYEE.EMP WHERE COMM IS NOT NULL);
SELECT LOC FROM DEPARTMENT.DEPT  WHERE DEPTNO IN(SELECT DEPTNO FROM EMPLOYEE.EMP WHERE COMM IS NOT NULL AND DEPTNO=40);

