SELECT ENAME,DNAME FROM EMPLOYEE.EMP CROSS JOIN DEPARTMENT.DEPT;
SELECT ENAME,DNAME FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

SELECT ENAME,LOC FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO;
SELECT DNAME,SAL FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO WHERE DNAME='ACCOUNTING';
SELECT DNAME,SAL*12 FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO WHERE SAL>2340;
SELECT ENAME,DNAME FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO WHERE DNAME LIKE '%A%';
SELECT  ENAME,DNAME FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO WHERE JOB='SALESMAN';
SELECT DNAME,JOB FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO WHERE JOB LIKE'S%' AND DNAME LIKE'S%';
SELECT DNAME,MGR FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO WHERE MGR=7839;

SELECT DNAME,HIREDATE FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON DEPT.DEPTNO=EMP.DEPTNO 
WHERE HIREDATE>='1984-01-01' AND (DNAME='ACCOUNTING' OR DNAME='RESEARCH');

SELECT ENAME,DNAME FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON EMP.DEPTNO=DEPT.DEPTNO 
WHERE  COMM IS NOT NULL AND (EMP.DEPTNO=10 OR EMP.DEPTNO=30);

SELECT DNAME,EMPNO  FROM EMPLOYEE.EMP INNER JOIN DEPARTMENT.DEPT ON EMP.DEPTNO=DEPT.DEPTNO 
WHERE (EMPNO=7839 OR EMPNO=7902) AND LOC='NEW YORK';
