-- 1
SELECT E1.ENAME,
	   E2.ENAME 
       FROM EMPLOYEE.EMP E1,EMPLOYEE.EMP E2  WHERE E1.MGR=E2.EMPNO AND E1.JOB='CLERK';
       
-- 2
SELECT E1.ENAME,E2.JOB FROM EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 WHERE E1.MGR=E2.EMPNO AND (E2.DEPTNO=10 OR E2.DEPTNO=20);

-- 3
SELECT E1.ENAME,E2.SAL FROM EMPLOYEE.EMP E1 JOIN EMPLOYEE.EMP E2 ON E1.MGR=E2.EMPNO;

-- 4
SELECT E1.ENAME,E2.HIREDATE FROM EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 WHERE E1.MGR=E2.EMPNO AND (E1.HIREDATE<'1982-01-01');

-- 5
SELECT E1.ENAME,E2.COMM FROM EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.JOB='SALESMAN' AND E2.DEPTNO=30;

-- 6
SELECT E1.ENAME,E1.SAL,E2.ENAME,E2.SAL FROM EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.SAL>E2.SAL;

-- 7
SELECT E1.ENAME,E1.HIREDATE,E2.ENAME,E2.HIREDATE FROM 
	   EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 WHERE E1.MGR=E2.EMPNO 
       AND  E2.HIREDATE<E1.HIREDATE;

-- 8
SELECT E1.ENAME,E2.ENAME FROM 
       EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 
       WHERE E1.MGR=E2.EMPNO AND E1.JOB=E2.JOB;
       
-- 9
SELECT E1.ENAME,E2.ENAME FROM 
       EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 
       WHERE E1.MGR=E2.EMPNO AND E2.JOB='MANAGER';
       
-- 10
SELECT E1.ENAME,E1.SAL,E2.ENAME,E2.SAL FROM 
       EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 
       WHERE E1.MGR=E2.EMPNO AND (E2.SAL>E1.SAL) AND(E1.DEPTNO=10 OR E1.DEPTNO=20);
       
-- 11
SELECT E1.ENAME,E2.ENAME,E2.JOB  FROM 
       EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 
       WHERE E1.MGR=E2.EMPNO;

-- 12
SELECT E1.ENAME,E2.SAL FROM 
       EMPLOYEE.EMP E1,EMPLOYEE.EMP E2 
       WHERE E1.MGR=E2.EMPNO AND E2.SAL LIKE '%50';
       



