-- 1
SELECT MIN(SAL) FROM EMP WHERE SAL>(SELECT MIN(SAL) FROM EMP);

-- 2
SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP
 WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP))));
 
 -- 3
 SELECT ENAME FROM EMP WHERE SAL IN(SELECT MAX(SAL) FROM EMP WHERE 
 SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP)));
 
 -- 4
 SELECT EMPNO FROM EMP WHERE SAL IN(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP));
 
 -- 5
 SELECT DNAME FROM DEPARTMENT.DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE SAL =(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE
 SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP)))));
 
 -- 6
 SELECT * FROM EMP WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP));
 
 -- 7
 SELECT ENAME FROM EMP WHERE HIREDATE=(SELECT MAX(HIREDATE) FROM EMP 
                       WHERE HIREDATE<(SELECT MAX(HIREDATE) FROM EMP));
 
 -- 8
 SELECT LOC FROM DEPARTMENT.DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP));
 
 -- 9
 SELECT * FROM EMP WHERE SAL=(SELECT MIN(SAL) FROM EMP 
                   WHERE SAL>(SELECT MIN(SAL) FROM EMP 
                   WHERE SAL>(SELECT MIN(SAL) FROM EMP 
                   WHERE SAL>(SELECT MIN(SAL) FROM EMP 
                   WHERE SAL>(SELECT MIN(SAL) FROM EMP
                   WHERE SAL>(SELECT MIN(SAL) FROM EMP
                   WHERE SAL>(SELECT MIN(SAL) FROM EMP)))))));
                   
-- 10
SELECT DNAME FROM DEPARTMENT.DEPT
          WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE SAL =(SELECT MAX(SAL) FROM EMP 
          WHERE SAL<(SELECT MAX(SAL) FROM EMP)));