CREATE TABLE CAPGEMINI(EMP_ID Integer(4) PRIMARY KEY,
					  EMPNAME VARCHAR(30) NOT NULL,
                      DESIGNATION VARCHAR (20) NOT NULL,
                      PERFORMANCE VARCHAR(20) NOT NULL,
                      LOCATION VARCHAR(20) NOT NULL
				);
INSERT INTO CAPGEMINI VALUES(101,"PRIYA","DEVELOPER","Excellent","Delhi");
INSERT INTO CAPGEMINI VALUES(102,"AMMY","ANALYST","AWESOME","NOIDA");
INSERT INTO CAPGEMINI VALUES(103,"GV","TRAINER","BRILLIANT","BANGLORE");
INSERT INTO CAPGEMINI VALUES(104,"KINHA","DEVELOPER","NICE","MUMBAI");
INSERT INTO CAPGEMINI VALUES(105,"YAMAN","RISK_ANALYST","GOOD","HARYANA");
SELECT * FROM CAPGEMINI;
ALTER  TABLE CAPGEMINI RENAME TO COGNIZANT;
SELECT * FROM COGNIZANT;
ALTER TABLE COGNIZANT ADD EMAIL VARCHAR(100);
SELECT * FROM COGNIZANT;
ALTER TABLE COGNIZANT CHANGE EMAIL EMP_EMAIL_ID VARCHAR(100);
SELECT * FROM COGNIZANT;
DELETE FROM COGNIZANT WHERE EMP_ID=102;
SELECT * FROM COGNIZANT;
DROP TABLE COGNIZANT;
